// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDov1xr11BjXXfQ4IVi6tmPPPSdEvLGMsY',
    appId: '1:886823707196:web:38a861b8db2a8ec7355939',
    messagingSenderId: '886823707196',
    projectId: 'ecoquest-1eeae',
    authDomain: 'ecoquest-1eeae.firebaseapp.com',
    storageBucket: 'ecoquest-1eeae.firebasestorage.app',
    measurementId: 'G-MXZEFTQ7YS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUqZh1zd7WnP70VcFmMqAEhA4qJFeUe88',
    appId: '1:886823707196:android:a6595bcaef21cf04355939',
    messagingSenderId: '886823707196',
    projectId: 'ecoquest-1eeae',
    storageBucket: 'ecoquest-1eeae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9K5y1lzdQo2r5pPZFyR8el-fN13WAKQU',
    appId: '1:886823707196:ios:30892643d97cdf14355939',
    messagingSenderId: '886823707196',
    projectId: 'ecoquest-1eeae',
    storageBucket: 'ecoquest-1eeae.firebasestorage.app',
    iosBundleId: 'com.example.ecoQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9K5y1lzdQo2r5pPZFyR8el-fN13WAKQU',
    appId: '1:886823707196:ios:30892643d97cdf14355939',
    messagingSenderId: '886823707196',
    projectId: 'ecoquest-1eeae',
    storageBucket: 'ecoquest-1eeae.firebasestorage.app',
    iosBundleId: 'com.example.ecoQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDov1xr11BjXXfQ4IVi6tmPPPSdEvLGMsY',
    appId: '1:886823707196:web:69030f234559ed01355939',
    messagingSenderId: '886823707196',
    projectId: 'ecoquest-1eeae',
    authDomain: 'ecoquest-1eeae.firebaseapp.com',
    storageBucket: 'ecoquest-1eeae.firebasestorage.app',
    measurementId: 'G-PC9R7PWLHY',
  );
}
